on: [push]
name: Linux_Container_Workflow 

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:

    - name: 'checkout the repo'
      uses: actions/checkout@v4

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: tncontaineregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push to registry'
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile_client
        push: true
        tags: tncontaineregistry.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}